### ISSUE TITLE
Update First Page

### ISSUE THREAD

**Issue by vineysindhu** [nwautomator/gsu-dissertation-template#1]
Hi,

Thank you for this template. It helped me a lot. However, I am not able to find, how to update the first page. I got feedback from graduate services to update Advisor name, PhD instead of Dr. Advisor name on the first page. Also, to add abstract to the first page instead of a separate page. I am not able to find the boiler which creates the first page of the thesis. I request your immediate assistance on this.

Also, graduate services asked me to add link to the tables and figures on the list of tables and list of figures page. Means instead of just name of the tables and figures it should be a link to that table of figure. It will be great if you can help me to do this as well.

I will appreciate your assistance on these updates.

Regards
Viney Sindhu

**Comment by nwautomator** [comment]
I've changed the advisor template so that you no longer see "Dr." in the generated document. This means you'll need to input your advisor's name and title into `boiler/advisor.tex`. For the table of contents and list of figures and tables, you should now be able to click on them in the generated PDF document to go directly to the page. For the abstract page, you can place it anywhere you'd like in `main.tex` if the current placement isn't what you want. Thanks for the feedback!

**Comment by vineysindhu** [comment]
Thank you for your quick response. It is working perfectly fine now. I really appreciate your help on this.
